### ISSUE TITLE
0.12 missing js build

### ISSUE THREAD

**Issue by whodidthis** [matthiasn/inspect#9]
I think the latest release is missing the javascript files (`inspect-0.1.12.jar/public/inspect/js` empty), might come as a shock to people trying this lib out hehe

**Comment by matthiasn** [comment]
Thanks for spotting this, I think a new line in `project.clj` was the problem as apparently a `lein clean` is run automatically first when calling `lein deploy clojars`. But this deleted the JS file first before deploying:
         
    :clean-targets ^{:protect false} ["resources/public/inspect/js/build/"]

Should be fixed now in 0.1.13.
